"""
tests/optimise/test_optimisation_layer3.py
───────────────────────────────────────────
Step 4 validation — first true optimisation (design §11 Layer 3).

Unfixes the sizing variables and solves the single-year MILP, then validates
the optimum three ways:

  Layer 3A  Solver sanity:    MILP terminates optimal; sizing within bounds.
  Layer 3B  Global optimum:   free savings_npv ≥ any fixed sizing evaluated
                              under the *same* Pyomo objective (rigorous —
                              uses the benchmark sizing as the fixed point).
  Layer 3C  Oracle agreement: the Pyomo optimum, re-evaluated through the
                              FinanceEngine oracle (PlantEngine RTC dispatch,
                              full 25-year re-simulation), reproduces the
                              Pyomo objective within tolerance, and Pyomo's
                              ToD-optimal dispatch is ≥ the RTC heuristic.
  Layer 3D  vs Optuna:        Pyomo savings_npv ≥ Optuna best (reference in
                              optuna_reference.json).  Documented finding:
                              the live Optuna run found ZERO feasible trials
                              under the current config, so this bound is
                              trivially satisfied — see the difference report.

Reference data
──────────────
``optuna_reference.json`` is generated by the existing SolverEngine
(1500 trials, seed 42, current config) — regenerate with the snippet in
``_OPTUNA_REGEN_HINT`` if the config changes.

C-rate divergence (documented)
──────────────────────────────
solver.yaml exposes bess_charge/discharge_c_rate as scope:current, so Optuna
optimises them; the Pyomo model fixes C-rate per D3 (reads ``max`` = 1.0).
The benchmark sizing (conftest) uses C-rate 1.0, matching Pyomo, so Layer 3B
is a clean comparison.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import numpy as np
import pyomo.environ as pyo
import pytest

from hybrid_plant.config_loader import FullConfig
from hybrid_plant.data_loader import load_timeseries_data
from hybrid_plant.optimise.build import build_single_year_model
from hybrid_plant.optimise.config import OptModelConfig
from hybrid_plant.optimise.params import OptParams, build_params
from hybrid_plant.optimise.report import compute_report
from hybrid_plant.optimise.solve import extract_dispatch, solve

_OPTUNA_REGEN_HINT = """
To regenerate tests/optimise/optuna_reference.json:
    from hybrid_plant.solver.solver_engine import SolverEngine
    solver = SolverEngine(config, data, Year1Engine(config, data),
                          FinanceEngine(config, data))
    res = solver.run(n_trials=1500, show_progress=False)   # seed from solver.yaml
"""

# Benchmark sizing (conftest SOLAR_WIND_PARAMS) — a known prior Optuna solution,
# C-rate 1.0 (consistent with the Pyomo fixed-C-rate convention).
_BENCH = {"S": 190.454972460807, "W": 116.130108575195,
          "P": 120.632227022855, "nb": 120}

_REF_PATH = Path(__file__).parent / "optuna_reference.json"


# ─────────────────────────────────────────────────────────────────────────────
# Module fixtures
# ─────────────────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def config(config) -> FullConfig:
    return config


@pytest.fixture(scope="module")
def data(config: FullConfig) -> dict:
    return load_timeseries_data(config)


@pytest.fixture(scope="module")
def params(config: FullConfig, data: dict) -> OptParams:
    return build_params(config, data)


@pytest.fixture(scope="module")
def opt_cfg() -> OptModelConfig:
    return OptModelConfig(horizon="single", solver_name="appsi_highs")


@pytest.fixture(scope="module")
def free_solve(opt_cfg: OptModelConfig, params: OptParams) -> dict:
    """Solve the free-sizing MILP once (~35 s). Module-scoped."""
    model  = build_single_year_model(opt_cfg, params, objective="savings_npv")
    status = solve(model, opt_cfg)
    dispatch = extract_dispatch(model, n_hours=8760)
    sizing = {
        "S":  float(pyo.value(model.S)),
        "W":  float(pyo.value(model.W)),
        "P":  float(pyo.value(model.P)),
        "nb": int(round(pyo.value(model.nb))),
    }
    return {"model": model, "status": status, "dispatch": dispatch, "sizing": sizing}


@pytest.fixture(scope="module")
def optuna_ref() -> dict:
    if not _REF_PATH.exists():
        pytest.skip(f"Optuna reference not found: {_REF_PATH}. {_OPTUNA_REGEN_HINT}")
    with _REF_PATH.open() as f:
        return json.load(f)


@pytest.fixture(scope="module")
def rtc_config(config: FullConfig) -> FullConfig:
    """Config clone with RTC dispatch (no evening window) for fair oracle check."""
    bess = copy.deepcopy(config.bess)
    bess["bess"]["dispatch"]["discharge_hours"] = []
    bess["bess"]["dispatch"]["charge_first"] = False
    return FullConfig(
        project=config.project, regulatory=config.regulatory,
        tariffs=config.tariffs, bess=bess,
        finance=config.finance, solver=config.solver,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Layer 3A — Solver sanity
# ─────────────────────────────────────────────────────────────────────────────

class TestLayer3ASolverSanity:

    @pytest.mark.slow
    def test_terminates_optimal(self, free_solve: dict) -> None:
        assert "optimal" in free_solve["status"]["status"].lower()

    @pytest.mark.slow
    def test_objective_finite_positive(self, free_solve: dict) -> None:
        import math
        v = free_solve["status"]["obj_val"]
        assert not math.isnan(v) and not math.isinf(v)
        assert v > 0, f"savings_npv not positive: {v:.2f}"

    @pytest.mark.slow
    def test_sizing_within_bounds(self, params: OptParams, free_solve: dict) -> None:
        s = free_solve["sizing"]
        assert params.s_min  <= s["S"]  <= params.s_max
        assert params.w_min  <= s["W"]  <= params.w_max
        assert params.p_min  <= s["P"]  <= params.p_max
        assert params.nb_min <= s["nb"] <= params.nb_max

    @pytest.mark.slow
    def test_nb_is_integer(self, free_solve: dict) -> None:
        nb_val = pyo.value(free_solve["model"].nb)
        assert abs(nb_val - round(nb_val)) < 1e-6, f"nb not integer: {nb_val}"

    @pytest.mark.slow
    def test_dispatch_feasible(self, params: OptParams, free_solve: dict) -> None:
        """C3 (new aux form), C8, ddraw≥0, soc≥0 hold at the optimum."""
        d   = free_solve["dispatch"]
        nb  = float(free_solve["sizing"]["nb"])
        E_b = nb * params.cs
        lhs = (params.lf * (d["sd"] + d["wd"] + params.eta_d * d["dis"]
                            - nb * params.aux_pc) + d["ddraw"])
        assert float(np.abs(lhs - params.load).max()) < 1e-3
        assert float(np.max(d["soc"])) <= E_b + 1e-5
        assert float(np.min(d["ddraw"])) >= -1e-6
        assert float(np.min(d["soc"]))   >= -1e-6


# ─────────────────────────────────────────────────────────────────────────────
# Layer 3B — Global-optimum guarantee
# ─────────────────────────────────────────────────────────────────────────────

class TestLayer3BGlobalOptimum:
    """
    The free optimum must dominate any fixed sizing evaluated under the same
    Pyomo objective.  Uses the benchmark sizing as the fixed comparison point.
    """

    @pytest.fixture(scope="class")
    def bench_fixed_npv(self, opt_cfg: OptModelConfig, params: OptParams) -> float:
        m = build_single_year_model(opt_cfg, params, fixed_sizing=_BENCH,
                                     objective="savings_npv")
        solve(m, opt_cfg)
        return float(pyo.value(m.obj))

    @pytest.mark.slow
    def test_free_geq_benchmark(self, free_solve: dict, bench_fixed_npv: float) -> None:
        free_npv = free_solve["status"]["obj_val"]
        assert free_npv >= bench_fixed_npv - 1.0, (
            f"Free optimum {free_npv/1e7:.2f} Cr < benchmark-fixed "
            f"{bench_fixed_npv/1e7:.2f} Cr — violates global-optimum guarantee"
        )

    @pytest.mark.slow
    def test_free_strictly_better_than_benchmark(
        self, free_solve: dict, bench_fixed_npv: float
    ) -> None:
        """Pyomo right-sizes: the free optimum should be materially better."""
        free_npv = free_solve["status"]["obj_val"]
        gain_cr = (free_npv - bench_fixed_npv) / 1e7
        print(f"\n[Layer3B] Right-sizing gain: free={free_npv/1e7:.1f} Cr "
              f"vs benchmark-fixed={bench_fixed_npv/1e7:.1f} Cr  (+{gain_cr:.0f} Cr)")
        assert gain_cr > 0


# ─────────────────────────────────────────────────────────────────────────────
# Layer 3C — FinanceEngine oracle agreement
# ─────────────────────────────────────────────────────────────────────────────

class TestLayer3COracleAgreement:
    """
    Re-evaluate the Pyomo optimum sizing through the FinanceEngine oracle
    (RTC dispatch, full 25-year re-sim) and confirm agreement.
    """

    @pytest.fixture(scope="class")
    def oracle_rtc(self, free_solve: dict, rtc_config: FullConfig, data: dict) -> dict:
        return compute_report(free_solve["sizing"], rtc_config, data, fast_mode=False)

    @pytest.mark.slow
    def test_oracle_savings_within_tolerance(
        self, free_solve: dict, oracle_rtc: dict
    ) -> None:
        """
        FinanceEngine RTC savings_npv must be within 5% of the Pyomo objective.
        Looser than Layer-2's 0.1% because dispatch differs (Pyomo optimal ToD
        vs PlantEngine RTC heuristic) and Pyomo carries an aux cost.
        """
        pyomo_npv  = free_solve["status"]["obj_val"]
        oracle_npv = oracle_rtc["savings_npv"]
        rel = abs(pyomo_npv - oracle_npv) / abs(oracle_npv)
        print(f"\n[Layer3C] Pyomo={pyomo_npv/1e7:.2f} Cr  "
              f"FinanceEngine RTC={oracle_npv/1e7:.2f} Cr  rel={rel*100:.2f}%")
        assert rel < 0.05, (
            f"Oracle disagreement {rel*100:.2f}% > 5%: "
            f"Pyomo={pyomo_npv/1e7:.2f} Cr, FinanceEngine={oracle_npv/1e7:.2f} Cr"
        )

    @pytest.mark.slow
    def test_pyomo_dispatch_beats_or_matches_heuristic(
        self, free_solve: dict, oracle_rtc: dict
    ) -> None:
        """
        Pyomo's globally-optimal ToD dispatch should yield savings_npv ≥
        the RTC heuristic (small margin allowed for the aux cost Pyomo carries
        but FinanceEngine omits).
        """
        pyomo_npv  = free_solve["status"]["obj_val"]
        oracle_npv = oracle_rtc["savings_npv"]
        # Pyomo carries aux (~nb/120 × 80 Cr); allow that as the only slack.
        nb = free_solve["sizing"]["nb"]
        aux_margin = nb / 120.0 * 80e7
        assert pyomo_npv >= oracle_npv - aux_margin, (
            f"Pyomo {pyomo_npv/1e7:.2f} Cr below RTC heuristic "
            f"{oracle_npv/1e7:.2f} Cr beyond aux margin {aux_margin/1e7:.1f} Cr"
        )

    @pytest.mark.slow
    def test_oracle_lcoe_plausible(self, oracle_rtc: dict) -> None:
        """LCOE for the optimum should be in a sane INR/kWh band."""
        lcoe = oracle_rtc["lcoe_inr_per_kwh"]
        assert 1.0 < lcoe < 10.0, f"LCOE implausible: {lcoe:.4f} INR/kWh"


# ─────────────────────────────────────────────────────────────────────────────
# Layer 3D — vs Optuna + difference report
# ─────────────────────────────────────────────────────────────────────────────

class TestLayer3DvsOptuna:

    @pytest.mark.slow
    def test_pyomo_geq_optuna_best(self, free_solve: dict, optuna_ref: dict) -> None:
        """
        Pyomo savings_npv ≥ Optuna best (§11 Layer 3 acceptance).

        Documented: the live 1500-trial Optuna found ZERO feasible solutions
        under the current config (every trial's savings_npv < 0 fails the
        minimum_savings_npv ≥ 0 gate), so its 'best' is a deeply negative
        infeasible point.  The Pyomo optimum is strongly positive — the bound
        holds with a very large margin.
        """
        pyomo_npv_cr  = free_solve["status"]["obj_val"] / 1e7
        optuna_npv_cr = optuna_ref["best_savings_npv_cr"]
        assert pyomo_npv_cr >= optuna_npv_cr, (
            f"Pyomo {pyomo_npv_cr:.2f} Cr < Optuna {optuna_npv_cr:.2f} Cr"
        )

    @pytest.mark.slow
    def test_optuna_reference_documented_zero_feasible(self, optuna_ref: dict) -> None:
        """
        Surface the Optuna degeneracy explicitly so it is not silently assumed
        to be a healthy comparison.  If a future config makes Optuna feasible,
        this test flags it (xfail-style documentation, not a hard requirement).
        """
        n_feasible = optuna_ref.get("n_feasible", None)
        print(f"\n[Layer3D] Optuna reference: n_feasible={n_feasible}, "
              f"best_savings_npv={optuna_ref['best_savings_npv_cr']:.1f} Cr")
        # This is a documentation assertion: under the committed reference,
        # Optuna found nothing feasible.  Not a model requirement.
        assert n_feasible == 0, (
            "Optuna reference now has feasible trials — regenerate and review "
            "the Layer 3 comparison narrative."
        )

    @pytest.mark.slow
    def test_difference_report(
        self, params: OptParams, free_solve: dict, optuna_ref: dict,
        rtc_config: FullConfig, data: dict
    ) -> None:
        """Print the Layer-3 explainable difference report (no hard assertions)."""
        s   = free_solve["sizing"]
        d   = free_solve["dispatch"]
        nb  = s["nb"]
        lf, eta_d, aux_pc, cs = params.lf, params.eta_d, params.aux_pc, params.cs

        meter = lf * (float(np.sum(d["sd"]) + np.sum(d["wd"]) + eta_d*np.sum(d["dis"]))
                      - nb*aux_pc*8760)
        bess  = eta_d * float(np.sum(d["dis"]))
        load_mwh = float(np.sum(params.load))
        op = optuna_ref["best_params"]

        print("\n" + "=" * 72)
        print("LAYER 3 — EXPLAINABLE DIFFERENCE REPORT")
        print("=" * 72)
        print(f"{'':18}{'Pyomo optimum':>18}{'Optuna best':>18}")
        print(f"{'Solar AC (MW)':18}{s['S']:>18.2f}{op['solar_capacity_mw']:>18.2f}")
        print(f"{'Wind (MW)':18}{s['W']:>18.2f}{op['wind_capacity_mw']:>18.2f}")
        print(f"{'PPA (MW)':18}{s['P']:>18.2f}{op['ppa_capacity_mw']:>18.2f}")
        print(f"{'BESS (cont)':18}{nb:>18d}{op['bess_containers']:>18d}")
        print(f"{'C-rate (chg)':18}{'1.00 (fixed D3)':>18}{op['charge_c_rate']:>18.3f}")
        print(f"{'savings_npv Cr':18}{free_solve['status']['obj_val']/1e7:>18.2f}"
              f"{optuna_ref['best_savings_npv_cr']:>18.1f}")
        print(f"{'feasible?':18}{'yes':>18}{'NO (0 trials)':>18}")
        print("-" * 72)
        print(f"RE penetration at optimum: {meter/load_mwh*100:.1f}% of load")
        print(f"BESS annual discharge:     {bess:,.0f} MWh ({bess/(nb*cs):.1f} equiv cycles)")
        print("\nEconomic drivers of the difference:")
        print(" 1. Optuna's TPE never explored the small-plant region; it sampled")
        print("    oversized configs (950 MW wind, 599 containers) with huge CAPEX")
        print("    and negative savings, so all 1500 trials failed the >=0 gate.")
        print(" 2. The flat-tariff Optuna objective is ToD-blind (Finding B): it")
        print("    cannot see the peak-shifting value that justifies the battery.")
        print(" 3. Pyomo right-sizes to ~Solar 72 / Wind 95 / PPA 56 / 19 cont,")
        print("    served by ToD-optimal dispatch, reaching ~1019 Cr savings_npv.")
        print("=" * 72)
