capex:

  solar:
    cost_per_mwp: 2.38e7
    ac_dc_ratio: 1.398

  wind:
    cost_per_mw: 7.0e7

  bess:
    cost_per_mwh: 0.90e7

  transmission:
    cost_per_km: 1.3e7
    length_km: 40


opex:

  solar:
    rate_lakh_per_mwp: 1.00        # Rs Lakh per DC MWp
    escalation_percent: 2.0

  wind:
    rate_lakh_per_mw: 12.00        # Rs Lakh per MW
    escalation_percent: 2.0

  bess:
    rate_lakh_per_mwh: 0.60        # Rs Lakh per MWh
    escalation_percent: 0.0

  solar_transmission:
    rate_lakh_per_mwp: 0.08        # Rs Lakh per DC MWp
    escalation_percent: 0.0

  wind_transmission:
    rate_lakh_per_mw: 0.08         # Rs Lakh per MW
    escalation_percent: 0.0

  land_lease:
    base_monthly_cost_crore: 1.00  # Rs Crore per month
    escalation_percent: 3.0

  insurance:
    percent_of_total_capex: 0.2    # % of total CAPEX
    escalation_percent: 0.0

  augmentation:
    enabled: false                  # future scope


regulatory_charges:

  ht:
    ctu_charge_inr_per_mw_per_month: 0.0
    stu_charge_inr_per_mw_per_month: 119172.80
    wheeling_charge_inr_per_kwh: 0.20
    banking_charge_inr_per_kwh: 0.00
    sldc_charge_inr_per_mw_per_month: 1440.00
    electricity_tax_inr_per_kwh: 0.0

  lt:
    ctu_charge_inr_per_mw_per_month: 0.0
    stu_charge_inr_per_mw_per_month: 119172.80
    wheeling_charge_inr_per_kwh: 0.97
    banking_charge_inr_per_kwh: 0.00
    sldc_charge_inr_per_mw_per_month: 1440.00
    electricity_tax_inr_per_kwh: 0.0


financing:

  structure: "levered_structured"

  debt_percent: 70
  equity_percent: 30

  corporate_tax_rate_percent: 25.17   # used only for WACC computation

  debt:
    interest_rate_percent: 8.5
    tenure_years: 25
    emi_structure: "fixed"

  equity:
    return_on_equity_percent: 20
    payout_type: "fixed_annual"